services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    networks:
      - mvr-hl
    ports:
      - 8090:8090
    volumes:
      - /opt/apps/beszel:/beszel_data
    labels:
      - "traefik.http.routers.beszel.entrypoints=web"
      - "traefik.http.routers.beszel.rule=Host(`stats.mvr.io`)"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    networks:
      - mvr-hl
    ports:
      - 3000:3000
    volumes:
      - /opt/apps/uptime-kuma:/app/data
    labels:
      - "traefik.http.routers.beszel.entrypoints=web"
      - "traefik.http.routers.beszel.rule=Host(`status.mvr.io`)"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN:?CLOUDFLARE_TUNNEL_TOKEN is not set}
    networks:
      - mvr-hl
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN
  
  ddns-updater:
    image: qmcgaw/ddns-updater:latest
    container_name: ddns-updater
    restart: unless-stopped
    networks:
      - mvr-hl
    ports:
      - 8000:8000
    volumes:
      - /opt/apps/ddns-updater:/updater/data

networks:
  mvr-hl:
    external: true