services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    networks:
      - mvr-hl
    ports:
      - 8090:8090
    volumes:
      - ${DATA_DIR:-/opt/apps}/beszel:/beszel_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.entrypoints=web"
      - "traefik.http.routers.beszel.rule=Host(`stats.mvr.io`)"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    networks:
      - mvr-hl
    ports:
      - 3001:3001
    volumes:
      - ${DATA_DIR:-/opt/apps}/uptime-kuma:/app/data

  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    networks:
      - mvr-hl
    volumes:
      - ${DATA_DIR:-/opt/apps}/tautulli:/config
    environment:
      - TZ=Europe/Zurich
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.entrypoints=web"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.mvr.io`)"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"

  ddns-updater:
    image: qmcgaw/ddns-updater:latest
    container_name: ddns-updater
    restart: unless-stopped
    networks:
      - mvr-hl
    ports:
      - 8000:8000
    volumes:
      - ${DATA_DIR:-/opt/apps}/ddns-updater:/updater/data

networks:
  mvr-hl:
    external: true