services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    networks:
      - mvr-hl
    environment:
      - TZ=Europe/Zurich
      - HOME=/config
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - ${DATA_DIR:-/opt/apps}/plex:/config
      - /mnt/temp/plex:/transcode
      - /mnt/media:/data
      - plex-logs:/config/Library/Application Support/Plex Media Server/Logs
      - plex-cache:/config/Library/Application Support/Plex Media Server/Cache
      - plex-metadata:/config/Library/Application Support/Plex Media Server/Metadata
      - plex-media:/config/Library/Application Support/Plex Media Server/Media
      - /etc/localtime:/etc/localtime:ro # Sync the container's time to the host's time
    ports:
      - 10003:32400

  sonarr-1080p:
    image: linuxserver/sonarr:latest
    container_name: sonarr-1080p
    restart: unless-stopped
    networks:
      - mvr-hl
    volumes:
      - ${DATA_DIR:-/opt/apps}/sonarr-1080p:/config
      - sonarr-1080p-backups:/config/Backups
      - sonarr-1080p-mediacover:/config/MediaCover
      - /mnt/media/TV-Shows/1080p:/tv
      - /mnt/temp/sabnzbd/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr-1080p.entrypoints=web"
      - "traefik.http.routers.sonarr-1080p.rule=Host(`sonarr-1080p.mvr.io`)"
      - "traefik.http.services.sonarr-1080p.loadbalancer.server.port=30027"

  sonarr-4k:
    image: linuxserver/sonarr:latest
    container_name: sonarr-4k
    restart: unless-stopped
    networks:
      - mvr-hl
    volumes:
      - ${DATA_DIR:-/opt/apps}/sonarr-4k:/config
      - sonarr-4k-backups:/config/Backups
      - sonarr-4k-mediacover:/config/MediaCover
      - /mnt/media/TV-Shows/4k:/tv
      - /mnt/temp/sabnzbd/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr-4k.entrypoints=web"
      - "traefik.http.routers.sonarr-4k.rule=Host(`sonarr-4k.mvr.io`)"
      - "traefik.http.services.sonarr-4k.loadbalancer.server.port=30028"

  radarr-1080p:
    image: linuxserver/radarr:latest
    container_name: radarr-1080p
    restart: unless-stopped
    networks:
      - mvr-hl
    volumes:
      - ${DATA_DIR:-/opt/apps}/radarr-1080p:/config
      - radarr-1080p-backups:/config/Backups
      - radarr-1080p-mediacover:/config/MediaCover
      - /mnt/media/Movies/1080p:/movies
      - /mnt/temp/sabnzbd/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr-1080p.entrypoints=web"
      - "traefik.http.routers.radarr-1080p.rule=Host(`radarr-1080p.mvr.io`)"
      - "traefik.http.services.radarr-1080p.loadbalancer.server.port=30025"

  radarr-4k:
    image: linuxserver/radarr:latest
    container_name: radarr-4k
    restart: unless-stopped
    networks:
      - mvr-hl
    volumes:
      - ${DATA_DIR:-/opt/apps}/radarr-4k:/config
      - radarr-4k-backups:/config/Backups
      - radarr-4k-mediacover:/config/MediaCover
      - /mnt/media/Movies/4k:/movies
      - /mnt/temp/sabnzbd/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr-4k.entrypoints=web"
      - "traefik.http.routers.radarr-4k.rule=Host(`radarr-4k.mvr.io`)"
      - "traefik.http.services.radarr-4k.loadbalancer.server.port=30026"

  ombi:
    image: 	lscr.io/linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    networks:
      - mvr-hl
    volumes:
      - ${DATA_DIR:-/opt/apps}/ombi:/config
    ports:
      - 10004:3579

networks:
  mvr-hl:
    external: true

volumes:
  plex-logs:
  plex-cache:
  plex-metadata:
  plex-media: 
  sonarr-1080p-backups:
  sonarr-1080p-mediacover:
  sonarr-4k-backups:
  sonarr-4k-mediacover:
  radarr-1080p-backups:
  radarr-1080p-mediacover:
  radarr-4k-backups:
  radarr-4k-mediacover:
