services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    networks:
      - mvr-hl
    environment:
      - TZ=Europe/Zurich
      - HOME=/config
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - ${DATA_DIR:-/opt/apps}/plex:/config
      - /mnt/temp/plex:/transcode
      - /mnt/media:/data
      - plex-logs:/config/Library/Application Support/Plex Media Server/Logs
      - plex-cache:/config/Library/Application Support/Plex Media Server/Cache
      - plex-metadata:/config/Library/Application Support/Plex Media Server/Metadata
      - plex-media:/config/Library/Application Support/Plex Media Server/Media
      - /etc/localtime:/etc/localtime:ro # Sync the container's time to the host's time
    ports:
      - 10003:32400

  sonarr-1080p:
    image: linuxserver/sonarr:latest
    container_name: sonarr-1080p
    restart: unless-stopped
    networks:
      - mvr-hl
    volumes:
      - ${DATA_DIR:-/opt/apps}/sonarr-1080p:/config
      - sonarr-1080p-backups:/config/Backups
      - sonarr-1080p-mediacover:/config/MediaCover
      - /mnt/media/TV-Shows/1080p:/tv
      - /mnt/temp/sabnzbd/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr-1080p.entrypoints=web"
      - "traefik.http.routers.sonarr-1080p.rule=Host(`sonarr-1080p.mvr.io`)"
      - "traefik.http.services.sonarr-1080p.loadbalancer.server.port=30027"

networks:
  mvr-hl:
    external: true

volumes:
  plex-logs:
  plex-cache:
  plex-metadata:
  plex-media: 
  sonarr-1080p-backups:
  sonarr-1080p-mediacover:
