services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    command:
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
    networks:
      - mvr-hl
    ports:
      - 80:80
      - 443:443
      # Webinterface
      - 8080:8080


networks:
  mvr-hl:
    name: mvr-hl
    external: false 
