services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    command:
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=mvr-hl
      - --providers.docker.watch=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - mvr-hl
    ports:
      - 80:80
      - 443:443
      # Webinterface
      - 8080:8080


networks:
  mvr-hl:
    name: mvr-hl
    external: false 
