services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    networks:
      - mvr-hl
    ports:
      - 80:80
      - 443:443


networks:
  mvr-hl:
    name: mvr-hl
    external: false 
