services:
  pangolin:
    image: fosrl/pangolin:1.6.2
    container_name: pangolin
    restart: unless-stopped
    volumes:
      - /opt/apps/pangolin:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "10s"
      timeout: "10s"
      retries: 15

  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - /opt/apps/pangolin/traefik:/etc/traefik:ro # Volume to store the Traefik configuration
      - /opt/apps/pangolin/letsencrypt:/letsencrypt # Volume to store the Let's Encrypt certificates
      -  /opt/apps/pangolin/traefik/logs:/var/log/traefik # Volume to store Traefik logs

networks:
  default:
    driver: bridge
    name: pangolin