services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    networks:
      - mvr-hl
    volumes:
      - paperless-redis:/data
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    volumes:
      - ${DATA_DIR:-/opt/apps}/paperless/data:/usr/src/paperless/data
      - /mnt/docs:/usr/src/paperless/media
      - ${DATA_DIR:-/opt/apps}/paperless/export:/usr/src/paperless/export
      - ${DATA_DIR:-/opt/apps}/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_URL: http://docs.mvr.io
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY:?PAPERLESS_SECRET_KEY is not set}
      PAPERLESS_TIME_ZONE: Europe/Zurich
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_OCR_LANGUAGES: deu eng
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.entrypoints=web"
      - "traefik.http.routers.paperless.rule=Host(`docs.mvr.io`)"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
    networks:
      - mvr-hl

  # Note: PostgreSQL is external service. You can find more information about the configuration here:
  # https://hub.docker.com/_/postgres
  nextcloud-db:
    # Note: Check the recommend version here: https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#server
    image: postgres:alpine
    restart: always
    networks:
      - mvr-hl
    volumes:
      - ${DATA_DIR:-/opt/apps}/nextcloud/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_POSTGRES_PASSWORD:?NEXTCLOUD_POSTGRES_PASSWORD is not set}

  # Note: Redis is an external service. You can find more information about the configuration here:
  # https://hub.docker.com/_/redis
  nextcloud-redis:
    image: redis:alpine
    restart: always
    networks:
      - mvr-hl
    volumes:
      - nextcloud-redis:/data
  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8089:80
    networks:
      - mvr-hl
    volumes:
      - ${DATA_DIR:-/opt/apps}/nextcloud/config:/var/www/html
      - /mnt/files:/var/www/html/data
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_POSTGRES_PASSWORD:?NEXTCLOUD_POSTGRES_PASSWORD is not set}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:?NEXTCLOUD_ADMIN_PASSWORD is not set}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:?NEXTCLOUD_ADMIN_USER is not set}
      - REDIS_HOST=nextcloud-redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=web"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.mvr.io`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    depends_on:
      - nextcloud-redis
      - nextcloud-db

networks:
  mvr-hl:
    external: true

volumes:
  paperless-redis:
  nextcloud-redis: