services:
  portainer:
    image: portainer/portainer-ce:2.29.2
    container_name: portainer
    restart: unless-stopped
    ports:
      - 80:8000
      - 443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/apps/portainer:/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN:?Cloudflare Tunnel token is required}
