services:

  #
  # Utilities
  #
  myspeed:
    image: germannewsmaker/myspeed:latest
    container_name: myspeed
    restart: unless-stopped
    networks:
      - mvr-hl
    volumes:
      - ${DATA_DIR:-/opt/apps}/myspeed:/myspeed/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myspeed.entrypoints=web"
      - "traefik.http.routers.myspeed.rule=Host(`speedtest.mvr.io`)"
      - "traefik.http.services.myspeed.loadbalancer.server.port=5216"

  convertx: 
    image: ghcr.io/c4illin/convertx:latest
    container_name: convertx
    restart: unless-stopped
    volumes:
      - ${DATA_DIR:-/opt/apps}/convertx:/app/data
    environment:
      - ALLOW_UNAUTHENTICATED=true
      - HTTP_ALLOWED=true
    networks:
      - mvr-hl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.convertx.entrypoints=web"
      - "traefik.http.routers.convertx.rule=Host(`convert.mvr.io`)"
      - "traefik.http.services.convertx.loadbalancer.server.port=3000"

  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    volumes:
      - ${DATA_DIR:-/opt/apps}/stirling-pdf/configs:/configs
      - ${DATA_DIR:-/opt/apps}/stirling-pdf/pipeline:/pipeline
      - /usr/share/tessdata # Required for extra OCR languages
      - /customFiles
      - /logs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
    networks:
      - mvr-hl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.entrypoints=web"
      - "traefik.http.routers.stirling-pdf.rule=Host(`pdf.mvr.io`)"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"

  changedetection: 
    image: dgtlmoon/changedetection.io:latest
    container_name: changedetection
    restart: unless-stopped
    volumes:
      - ${DATA_DIR:-/opt/apps}/changedetection:/datastore
    networks:
      - mvr-hl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.changedetection.entrypoints=web"
      - "traefik.http.routers.changedetection.rule=Host(`changedetection.mvr.io`)"
      - "traefik.http.services.changedetection.loadbalancer.server.port=5000"

  karakeep:
    image: ghcr.io/karakeep-app/karakeep:release
    restart: unless-stopped
    container_name: karakeep
    depends_on:
      - karakeep-chrome
      - karakeep-meilisearch
    volumes:
      - ${DATA_DIR:-/opt/apps}/karakeep/config:/data
    environment:
      MEILI_ADDR: http://karakeep-meilisearch:7700
      BROWSER_WEB_URL: http://karakeep-chrome:9222
      OLLAMA_BASE_URL: http://ollama.mvr.io
      INFERENCE_TEXT_MODEL: gemma3n:latest
      INFERENCE_IMAGE_MODEL: gemma3n:latest
      NEXTAUTH_URL: http://keep.mvr.io
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:?NEXTAUTH_SECRET is not set}
      DATA_DIR: /data # DON'T CHANGE THIS
    networks:
      - mvr-hl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.karakeep.entrypoints=web"
      - "traefik.http.routers.karakeep.rule=Host(`keep.mvr.io`)"
      - "traefik.http.services.karakeep.loadbalancer.server.port=3000"

  karakeep-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: karakeep-chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - mvr-hl
  karakeep-meilisearch:
    image: getmeili/meilisearch:v1.13.3
    container_name: karakeep-meilisearch
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:?MEILI_MASTER_KEY is not set}
    volumes:
      - ${DATA_DIR:-/opt/apps}/karakeep/meilisearch:/meili_data
    networks:
      - mvr-hl

  #
  # HomeLab
  #
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    restart: unless-stopped
    environment:
      - PRIMARY=${NEBULA_SYNC_PRIMARY}
      - REPLICAS=${NEBULA_SYNC_REPLICAS}
      - FULL_SYNC=false
      - SYNC_CONFIG_DNS=true
      - SYNC_CONFIG_RESOLVE=true
      - SYNC_CONFIG_DATABASE=true
      - SYNC_CONFIG_MISC=true
      - SYNC_GRAVITY_GROUP=true
      - SYNC_GRAVITY_AD_LIST=true
      - SYNC_GRAVITY_AD_LIST_BY_GROUP=true
      - SYNC_GRAVITY_DOMAIN_LIST=true
      - SYNC_GRAVITY_CLIENT=true
      - RUN_GRAVITY=true
      - CRON=20,50 * * * *
  
  truenas-auto-update:
    image: ghcr.io/marvinvr/truenas-auto-update:latest
    container_name: truenas-auto-update
    restart: unless-stopped
    environment:
      - BASE_URL=${TRUENAS_BASE_URL}
      - API_KEY=${TRUENAS_API_KEY}
      - APPRISE_URLS=${TRUENAS_APPRISE_URLS}
      - CRON_SCHEDULE=0 4 * * *
      - NOTIFY_ON_SUCCESS=false

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    networks:
      - mvr-hl
    volumes:
      - ${DATA_DIR:-/opt/apps}/ombi:/config
    ports:
      - 10004:3579

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Zurich
      - PORT=5055 #optional
    ports:
      - 10007:5055
    volumes:
      - ${DATA_DIR:-/opt/apps}/jellyseerr:/app/config

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - ${DATA_DIR:-/opt/apps}/homarr:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY:?SECRET_ENCRYPTION_KEY is not set}
    networks:
      - mvr-hl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.entrypoints=web"
      - "traefik.http.routers.homarr.rule=Host(`dash.mvr.io`)"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"

  flaresolverr:
    image: ghcr.io/yoori/flare-bypasser:latest
    container_name: flaresolverr
    restart: unless-stopped
    networks:
      - mvr-hl
    environment:
      UNUSED: "false"
      # FORKS: "5:3" #< Uncomment if you work with sites with ustable challenge loading (start additional 3 forks after 5 seconds).
      DEBUG: "false"
      VERBOSE: "false"
      SAVE_CHALLENGE_SCREENSHOTS: "false"
    labels:
      - traefik.enable=true
      - traefik.http.routers.flaresolverr.entrypoints=web
      - traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.mvr.io`)
      - traefik.http.services.flaresolverr.loadbalancer.server.port=8080

  omni-tools:
    image: iib0011/omni-tools:latest
    container_name: omni-tools
    restart: unless-stopped
    networks:
      - mvr-hl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omni-tools.entrypoints=web"
      - "traefik.http.routers.omni-tools.rule=Host(`tools.mvr.io`)"
      - "traefik.http.services.omni-tools.loadbalancer.server.port=80"

  #
  # AI
  #
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    networks:
      - mvr-hl
    volumes:
      - ${DATA_DIR:-/opt/apps}/open-webui:/app/backend/data
    ports:
      - 10001:8080

networks:
  mvr-hl:
    external: true 