services:

  #
  # Utilities
  #
  myspeed:
    image: germannewsmaker/myspeed:latest
    container_name: myspeed
    restart: unless-stopped
    networks:
      - mvr-hl
    volumes:
      - /opt/apps/myspeed:/myspeed/data
    ports:
      - 5216:5216
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myspeed.entrypoints=web"
      - "traefik.http.routers.myspeed.rule=Host(`speedtest.mvr.io`)"
      - "traefik.http.services.myspeed.loadbalancer.server.port=5216"
  
  convertx: 
    image: ghcr.io/c4illin/convertx:latest
    container_name: convertx
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /opt/apps/convertx:/app/data
    environment:
      - ALLOW_UNAUTHENTICATED=true
      - HTTP_ALLOWED=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.convertx.entrypoints=web"
      - "traefik.http.routers.convertx.rule=Host(`convert.mvr.io`)"
      - "traefik.http.services.convertx.loadbalancer.server.port=3000"
#  changedetection:
#  nebula-sync:
#  ombi:
#  open-webui:
#  tautulli:
#  truenas-auto-update:
#  unsend:
  

networks:
  mvr-hl:
    external: true 